version: '3'
networks:
  local_network:
    external: true
services:
  student-management-server:
    image: student-management-server
    container_name: student-management-server
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_NAME=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE_NAME=student_management
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 3000:3000
    networks:
      - local_network
